Add static typing to pubtools-sign
release-engineering/pubtools-sign pull request #21
Opened 2024-01-08 09:02 UTC by querti

The mypy checks pass with strict mode enabled. Test environments were updated to 3.11 so that new typing syntax would be recognized. Some minor bug fixes were performed for issues that were detected by mypy. For other issues, where there wasn't an obvious solution, I added TOFIX comments.

2024-01-09 02:19 UTC, zxiong approved these changes

2024-01-09 14:11 UTC, midnightercz requested changes

2024-01-09 14:11 UTC, midnightercz commented on src/pubtools/sign/signers/cosignsigner.py
> +    signing_key: str | None = None,
Default values here should be changed to "" instead of None for signing_key and config. For digest and reference to []

2024-01-09 14:11 UTC, midnightercz commented on src/pubtools/sign/signers/msgsigner.py
> +# TOFIX: inconsistency: in this function config can be None,
config default should be set to ""

2024-01-09 14:11 UTC, midnightercz commented on src/pubtools/sign/signers/msgsigner.py
> +# TOFIX: should raw be a boolean? Why is it None?
yeah it should be false

2024-01-09 14:11 UTC, midnightercz commented on src/pubtools/sign/signers/msgsigner.py
> +    log_level: str | None = None,
log_level default should be set to "INFO"

2024-01-09 14:11 UTC, midnightercz commented on src/pubtools/sign/signers/msgsigner.py
> +    signing_key: str | None = None,
signing_key, task_id, config_file should be set to ""

2024-01-10 08:15 UTC, querti commented on .github/workflows/tox-tests.yml
> -  py37:
Changed the typing syntax to be compatible with Python 3.7 and restored the 3.7 testing environment.

2024-01-10 08:15 UTC, querti commented on src/pubtools/sign/operations/base.py
> +    def doc_arguments(cls: Type[T]) -> Dict[str, Any]:
Changed to Type[Self].

2024-01-10 08:19 UTC, querti commented
@midnightercz some of the TOFIX changes are non-trivial, so would it be OK if you were the one to fix them, since you have a better understanding of the code? I would like to avoid introducing new issues due to a lack of understanding or not testing the code.

Thanks!

2024-01-10 09:50 UTC, emilyzheng approved these changes

2024-01-10 12:06 UTC, merged